apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: first-aid-kit

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: first-aid-kit
  app.kubernetes.io/component: web

images:
  - name: first-aid-kit
    newTag: latest
